DROP TABLE USERS;
DROP TABLE DOCUMENTDEFINITION;
DROP TABLE DOCUMENTDATA;

CREATE TABLE USERS
(
  USERID INT PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(30) UNIQUE,
  PASSCODE VARCHAR(128)
);

CREATE TABLE DOCUMENTDEFINITION
(
  DOCUMENTID INT PRIMARY KEY AUTO_INCREMENT,
  DESCRIPTION VARCHAR(60) UNIQUE
);

CREATE TABLE DOCUMENTDATA
(
  DOCUMENTID INT,
  SECTIONID INT,
  SECURITYGROUP INT,
  SECTIONTEXT TEXT,
  PRIMARY KEY (DOCUMENTID, SECTIONID)
);